Implementar estratégia inicial
lav25balthazar/mini pull request #21
Opened 2023-02-15 19:47 UTC by lav25balthazar

2023-02-15 22:38 UTC, jgabriellacerda requested changes

2023-02-15 22:38 UTC, jgabriellacerda commented on initial_strategy.cpp
> +  if (strategyB == true)
E se tiver mais de um pino true?

2023-02-15 22:38 UTC, jgabriellacerda commented on initial_strategy.cpp
> +  this->moves = moves;
Como vc inicializou o moves na linha de cima, não precisa atribuir dessa forma.

2023-02-15 22:38 UTC, jgabriellacerda commented on initial_strategy.cpp
> +    this->moves.pop_front();
Fazendo isso vc vai esvaziar a lista de moves de uma vez só, vai acabar não executando nenhum

2023-02-16 12:16 UTC, lav25balthazar commented on initial_strategy.cpp
> +  this->moves = moves;
Eu tinha deixado só a de baixo, mas aí não compilou, tinha dado erro nela, só foi assim, o porquê eu não sei, agora eu tirei o de cima e foi, eu sou uma piada pra essa IDE kkkkkkkkkkkkkkk

2023-02-16 17:24 UTC, jgabriellacerda requested changes

2023-02-16 17:24 UTC, jgabriellacerda commented on initial_strategy.cpp
> +    if (move_status == true){
Essa é a ideia, mas não precisa escrever esse código 3 vezes já q ele não vai executar os 3 moves de uma vez. O código ficar chamando essa função e ela deve usar o current_move pra saber qual ta executando.

2023-02-16 21:43 UTC, jgabriellacerda requested changes

2023-02-16 21:43 UTC, jgabriellacerda commented on initial_strategy.cpp
>      this->moves.pop_front();
Você não deve remover um Move da lista sem que o current_move tenha acabado, senão ele vai remover todos em sequência.

2023-02-17 20:48 UTC, jgabriellacerda requested changes

2023-02-17 20:48 UTC, jgabriellacerda commented on initial_strategy.cpp
> +    return finished;
Faltou this

2023-02-17 20:48 UTC, jgabriellacerda commented on initial_strategy.cpp
> +  this->moves = moves;
Tem q inicializer o moves no "initializer list", igual o current_move

2023-02-17 20:48 UTC, jgabriellacerda commented on initial_strategy.cpp
> +    this->current_move = this->moves.front();
Só deve atualizar o current_move quando ele terminar de executar, ou seja, move_status igual true.

2023-02-22 16:37 UTC, jgabriellacerda approved these changes

2023-02-22 16:37 UTC, merged